# Terminal & color support
set -a terminal-features "tmux-256color:RGB"

# Prefix
set -g prefix C-SPACE

# Mouse support
set -g mouse on

# Indexing & renumbering
set -g base-index 1
set -g renumber-windows on

# Vi mode for copy mode
set -g mode-keys vi

# Escape time
set -sg escape-time 0

# Status bar minimal styling
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=blue bold"

# Status refresh
set -g status-interval 5
set -g status-right '#{?client_prefix, _ ,}#(timew | awk "/^ *Total/ {print \$NF}") #[bg=green,fg=black,bold]#(timew | awk "/^ *Tracking/ {print \" \" \$NF \" \"}")#[bg=default]'
set -g status-left "#S"   # session name

# Scripts
bind T display-popup -E -w 60% -h 40% -x C -y C "bash ~/.dotfiles/scripts/time.sh"
